name: img-upload # You can also change this to another name to avoid warning with existing group. 
services:
  frontend:
    container_name: pf-img-frontend
    build: .
    ports:
      - ${NGINX_PORT}:5899
    networks:
      - img-upload_pf-net
    environment:
      - NGINX_PROXY=${NGINX_PROXY}
      - NGINX_PORT=${NGINX_PORT}
networks:
  img-upload_pf-net: # Check by using `docker network ls` command
    external: true